#!/usr/bin/env python3
"""Generate research/rules/inventory.md from what is actually on disk.

Scans <workspace>/projects and <workspace>/pipelines, joins each slug with
its one-line description from rules/inventory_descriptions.toml, and writes
rules/inventory.md. Repos on disk but missing from the descriptions file get
a TODO marker (so the generated file is always complete and staleness is
visible instead of silent). Symlinked entries are skipped.

Usage: python3 gen_inventory.py [--workspace PATH]
"""
import argparse
import re
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from workspace_root import workspace  # noqa: E402  (one resolver; see its docstring)


def parse_desc_toml(text: str) -> dict:
    """Minimal parser for this file's constrained TOML subset:
    [section] headers and `key = "value"` lines. Avoids requiring
    python >= 3.11 (tomllib) on hosts where python3 is older."""
    data: dict = {}
    section: dict | None = None
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = re.fullmatch(r"\[([A-Za-z0-9_-]+)\]", line)
        if m:
            section = data.setdefault(m.group(1), {})
            continue
        m = re.fullmatch(r'([A-Za-z0-9_-]+)\s*=\s*"(.*)"', line)
        if m and section is not None:
            section[m.group(1)] = m.group(2)
    return data


def scan(root: Path) -> list[str]:
    if not root.is_dir():
        return []
    return sorted(
        p.name for p in root.iterdir()
        if p.is_dir() and not p.is_symlink() and not p.name.startswith(".")
        and (p / ".git").exists()  # repos only; skips helper dirs like projects/pipelines/
    )


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--workspace", default=str(workspace()))
    args = ap.parse_args()
    ws = Path(args.workspace)
    rules = ws / "research" / "rules"
    desc_path = rules / "inventory_descriptions.toml"
    out_path = rules / "inventory.md"

    desc = parse_desc_toml(desc_path.read_text()) if desc_path.exists() else {}

    lines = [
        "# Workspace inventory (generated)",
        "",
        f"Generated by `research-kit/tools/gen_inventory.py` on {date.today()}.",
        "Do not edit by hand — edit `inventory_descriptions.toml` and re-run.",
        "",
    ]
    todo = 0
    for kind in ("projects", "pipelines"):
        lines.append(f"## {kind}/")
        lines.append("")
        table = desc.get(kind, {})
        for slug in scan(ws / kind):
            d = table.get(slug, "")
            if not d:
                d = "TODO: add one-line description in inventory_descriptions.toml"
                todo += 1
            lines.append(f"- `{kind}/{slug}` — {d}")
        lines.append("")
        stale = sorted(set(table) - set(scan(ws / kind)))
        if stale:
            lines.append(
                f"*Described but not on disk (remove from toml?): {', '.join(stale)}*"
            )
            lines.append("")

    out_path.write_text("\n".join(lines))
    print(f"wrote {out_path} ({todo} missing descriptions)")
    sys.exit(0)


if __name__ == "__main__":
    main()
