#!/usr/bin/env python3
"""Nightly workspace convention sweep (run by host cron).

Runs check_docs.py and citations.py workspace-wide and writes a morning
report to ~/.claude/state/nightly_sweep_report.md ONLY when errors exist;
the SessionStart hook surfaces that file in the next session. Deterministic
linting only — no LLM involved.
"""
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

MAX_PER_TOOL = 25


def workspace() -> Path:
    env = os.environ.get("RESEARCH_WORKSPACE")
    if env:
        return Path(env)
    for cand in (Path.home() / "research", Path("/workspace")):
        if (cand / "research-kit").exists():
            return cand
    return Path.home() / "research"


def main() -> int:
    ws = workspace()
    tools = ws / "research-kit" / "tools"
    state = Path.home() / ".claude" / "state"
    state.mkdir(parents=True, exist_ok=True)
    report = state / "nightly_sweep_report.md"

    lines = [
        f"# Nightly convention sweep — {datetime.now():%Y-%m-%d}",
        "",
        "Generated by research-kit/tools/nightly_sweep.py (cron). Mention",
        "problems to the user at a natural moment and offer to fix them.",
        "",
    ]
    total = 0
    for tool in ("check_docs", "citations"):
        cmd = ["python3", str(tools / f"{tool}.py"), "--json"]
        if tool == "citations":
            cmd += ["--workspace", str(ws)]
        try:
            out = subprocess.run(
                cmd,
                capture_output=True, text=True, timeout=300,
            )
            data = json.loads(out.stdout)
        except Exception as e:
            lines += [f"## {tool}: sweep failed ({e})", ""]
            total += 1
            continue
        errs = [
            (r.get("scope", "?"), f)
            for r in data.get("repos", []) + [data.get("workspace", {})]
            for f in r.get("errors", [])
        ]
        total += len(errs)
        lines.append(f"## {tool}: {len(errs)} error(s)")
        for scope, f in errs[:MAX_PER_TOOL]:
            lines.append(f"- {scope}: {f.get('path', '?')} — {f.get('msg', '')}")
        if len(errs) > MAX_PER_TOOL:
            lines.append(f"- ... and {len(errs) - MAX_PER_TOOL} more")
        lines.append("")

    try:
        out = subprocess.run(
            ["python3", str(tools / "skill_links.py"), "--json", "--root", str(ws)],
            capture_output=True, text=True, timeout=120,
        )
        data = json.loads(out.stdout)
        issues = data.get("issues", [])
        total += len(issues)
        lines.append(f"## skill_links: {len(issues)} issue(s)")
        for issue in issues[:MAX_PER_TOOL]:
            lines.append(f"- {issue}")
        if len(issues) > MAX_PER_TOOL:
            lines.append(f"- ... and {len(issues) - MAX_PER_TOOL} more")
        lines.append("")
    except Exception as e:
        lines += [f"## skill_links: sweep failed ({e})", ""]
        total += 1

    if total > 0:
        report.write_text("\n".join(lines))
    elif report.exists():
        report.unlink()
    with open(state / "nightly_sweep.log", "a") as fh:
        fh.write(f"[{datetime.now().isoformat(timespec='seconds')}] {total} error(s)\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
